apiVersion: apps/v1
kind: Deployment
metadata:
  name: portals-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portals
  template:
    metadata:
      labels:
        app: portals
    spec:
      containers:
        - name: portals-server
          image: "portals"
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: portals-service
spec:
  type: NodePort
  selector:
    app: portals
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

