# https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html

name: Build and test
on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v3
      with: 
        distribution: temurin
        java-version: 17
    - name: Build and Test
      run: sbt -v test
    - name: Scalafmt scala
      run: sbt scalafmtCheckAll
    - name: Scalafmt sbt
      run: sbt scalafmtSbtCheck
    # - name: Build docs
    #   run: sbt doc
